#!/bin/bash

# Update Homebrew and upgrade packages
brew update && brew upgrade

# Backup existing .zshrc if it exists
if [ -f "$HOME/.zshrc" ]; then
  mv $HOME/.zshrc $HOME/.zshrc.bak
  echo "Existing .zshrc backed up to .zshrc.bak"
fi

# Install Oh My Zsh
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Install Bat
brew install bat

# Install Eza (modern replacement for ls)
brew install eza

# Install Neovim
brew install neovim

# Install Starship
brew install starship

# Define the ZSH_CUSTOM location
ZSH_CUSTOM=${ZSH_CUSTOM:-~/.oh-my-zsh/custom}

# Install zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-autosuggestions.git "${ZSH_CUSTOM}"/plugins/zsh-autosuggestions

# Install zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git "${ZSH_CUSTOM}"/plugins/zsh-syntax-highlighting

# Install zsh-autocomplete
git clone --depth 1 https://github.com/marlonrichert/zsh-autocomplete.git "${ZSH_CUSTOM}"/plugins/zsh-autocomplete

echo "Plugins installed: zsh-autosuggestions, zsh-syntax-highlighting, and zsh-autocomplete. Add them to the plugins list in your ~/.zshrc file."

# Install Oh My Posh
brew install jandedobbeleer/oh-my-posh/oh-my-posh

# Install p10k
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k
echo 'source ~/powerlevel10k/powerlevel10k.zsh-theme' >>~/.zshrc

# Instructions for the user
echo "Installation complete. Please restart your terminal or run 'source ~/.zshrc' for changes to take effect."
echo "To customize your new Zsh setup, open ~/.zshrc in your favorite text editor. For example, you can type 'nano ~/.zshrc' to edit it with nano."
echo "If you need to revert to your old Zsh configuration, your original .zshrc is saved as .zshrc.bak."
echo "To configure Starship, create or edit ~/.config/starship.toml"
echo "To use Oh My Posh, add 'eval \"$(oh-my-posh init zsh)\"' to your ~/.zshrc file"
